// packages/svelte/src/PrismWindow.svelte
<!--
  Prism Window Manager (@prism-wm), Svelte adapter
  Copyright (C) 2023-2026 Banshee Technologies S.L.
  Authors: Claudio González, Néstor González
  https://www.banshee.pro/

  Extracted from HomeDock OS: https://github.com/BansheeTech/HomeDockOS

  @license AGPL-3.0-or-later

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with this program. If not, see <https://www.gnu.org/licenses/>.

  SPDX-License-Identifier: AGPL-3.0-or-later
-->
<script lang="ts">
  import { onDestroy, onMount, type ComponentType } from "svelte";
  import { computeResize, centerDialog, computeUnsnapFlip, detectSnapEdge, prefersReducedMotion, PWM_MINIMIZE_ANIMATION_MS, PWM_OPEN_ANIMATION_MS, PWM_UNSNAP_ANIMATION_MS, UNSNAP_DRAG_THRESHOLD, type ResizeDirection, type UnsnapFlip, type WindowState } from "@prism-wm/core";
  import { cx, EMPTY_CLASSES, getPrismContext, resolveCapabilities, type PrismClassMap } from "./context.js";
  import ControlGlyph from "./ControlGlyph.svelte";
  import LoadingGlyph from "./LoadingGlyph.svelte";

  // Named `win`, not `window`, so `window.innerWidth` below is the global.
  export let win: WindowState;
  export let isActive: boolean;
  export let isMobile = false;
  export let taskbarHeight = 0;
  // Host class names, forwarded reactively by PrismWindowManager.
  export let classes: PrismClassMap = EMPTY_CLASSES;
  // A window-modal dialog belongs to this window: block and inert it.
  export let isBlocked = false;

  const ctx = getPrismContext();

  const RESIZE_DIRS: ResizeDirection[] = ["n", "s", "e", "w", "ne", "nw", "se", "sw"];
  const DOUBLE_CLICK_THRESHOLD = 300;

  // Which control sits where, per appearance. See PrismAppearance in core.
  $: controlOrder = ctx.appearance === "cupertino" ? (["close", "minimize", "maximize"] as const) : (["minimize", "maximize", "close"] as const);

  let dragging = false;
  let resizing = false;
  let keepAlive = true;
  let lastClick = 0;
  let unsnapTimer: ReturnType<typeof setTimeout> | null = null;
  let unsnapping = false;
  let flip: UnsnapFlip | null = null;

  // ---- Entrance animation ----------------------------------------------
  // A class the adapter drops after one run: on .pwm-window it would replay.
  let opening = !prefersReducedMotion();
  const openTimer = opening ? setTimeout(() => (opening = false), PWM_OPEN_ANIMATION_MS) : null;

  // ---- Minimize / restore animation ------------------------------------
  let minimizing = false;
  let restoring = false;
  let minimizeTimer: ReturnType<typeof setTimeout> | null = null;
  function onMinimizedChange(min: boolean) {
    if (minimizeTimer) clearTimeout(minimizeTimer);
    if (prefersReducedMotion()) {
      minimizing = false;
      restoring = false;
      return;
    }
    minimizing = min;
    restoring = !min;
    minimizeTimer = setTimeout(() => {
      minimizeTimer = null;
      minimizing = false;
      restoring = false;
    }, PWM_MINIMIZE_ANIMATION_MS);
  }

  $: caps = ((c) =>
    // A dialog is a window with fewer verbs:
    win.kind === "dialog" ? { ...c, resizable: false, minimizable: false, maximizable: false } : c)(resolveCapabilities(ctx.resolveConfig(win)));
  // Never asked for an external window: the host paints that body itself.
  $: resolved = (win.external ? null : ctx.resolveComponent(win)) as ComponentType | null;

  // ---- RAM manager: keep-alive gate for the body only ------------------
  let prevMinimized: boolean | undefined;
  $: if (win.isMinimized !== prevMinimized) {
    const first = prevMinimized === undefined;
    prevMinimized = win.isMinimized;
    // Skip on mount: a window that starts minimized shouldn't animate itself in.
    if (!first) onMinimizedChange(win.isMinimized);
    if (ctx.ram) {
      if (win.isMinimized) ctx.ram.onMinimize(win.id, () => (keepAlive = false));
      else {
        ctx.ram.onRestore(win.id);
        keepAlive = true;
      }
    }
  }

  // Re-centres as the height changes; stops once the user drags.
  let rootEl: HTMLElement | null = null;
  let userMoved = false;
  let sizeObserver: ResizeObserver | null = null;

  function recentre(h: number) {
    // Reported first: the drag clamp needs the true height, not the placeholder.
    ctx.store.setMeasuredHeight(win.id, h);
    if (userMoved) return;
    // Same centring rule as the store used, now with the measured height.
    const owner = win.modality === "window" && win.ownerId ? ctx.store.getWindowById(win.ownerId) : null;
    const at = centerDialog(win.width, h, { width: window.innerWidth, height: window.innerHeight }, owner);
    ctx.store.updateWindowPosition(win.id, at.x, at.y);
  }

  onMount(() => {
    if (!win.autoHeight || !rootEl) return;
    // onMount runs before paint, so the correction lands in the same frame.
    recentre(rootEl.offsetHeight);

    if (typeof ResizeObserver === "undefined") return;
    sizeObserver = new ResizeObserver(() => {
      const h = rootEl?.offsetHeight;
      if (h) recentre(h);
    });
    sizeObserver.observe(rootEl);
  });

  onDestroy(() => {
    sizeObserver?.disconnect();
    sizeObserver = null;
    if (unsnapTimer) clearTimeout(unsnapTimer);
    if (minimizeTimer) clearTimeout(minimizeTimer);
    if (openTimer) clearTimeout(openTimer);
    ctx.ram?.onRestore(win.id);
  });

  // ---- Style + class ---------------------------------------------------
  $: className = cx("pwm-window", isActive && "pwm-active", win.kind === "dialog" && "pwm-dialog", win.isMaximized && "pwm-maximized", isMobile && win.kind !== "dialog" && "pwm-fullscreen-mobile", dragging && "pwm-dragging", resizing && "pwm-resizing", win.isClosing && "pwm-closing", `pwm-${ctx.appearance}`, unsnapping && "pwm-unsnapping", minimizing && "pwm-minimizing", restoring && "pwm-restoring", opening && "pwm-opening", classes.window, isActive ? classes.windowActive : classes.windowInactive);

  $: style = buildStyle(win, isMobile, taskbarHeight, minimizing, flip);

  function buildStyle(w: WindowState, mobile: boolean, tb: number, keepVisible: boolean, f: UnsnapFlip | null): string {
    const z = `z-index:${w.zIndex};`;
    const hidden = w.isMinimized && !keepVisible ? "display:none;" : "";
    // Read by the pwm-unsnap keyframes;
    const vars = f ? `--pwm-unsnap-from:${f.transform};--pwm-unsnap-from-content:${f.contentTransform};` : "";
    // Dialogs keep their centred bounds on mobile; only plain windows go fullscreen.
    if (mobile && w.kind !== "dialog") return `${hidden}top:0;left:0;width:100vw;height:calc(100% - ${tb}px);${z}${vars}`;
    if (w.isMaximized) return `${hidden}top:0;left:0;width:100%;height:calc(100% - ${tb}px);${z}${vars}`;
    // Height omitted when the content decides: CSS caps it instead.
    const h = w.autoHeight ? "" : `height:${w.height}px;`;
    return `${hidden}top:${w.y}px;left:${w.x}px;width:${w.width}px;${h}${z}${vars}`;
  }

  // ---- Focus / controls ------------------------------------------------
  function onFocus() {
    if (!isActive) ctx.store.focusWindow(win.id);
  }

  // Focus on mousedown, minus the controls: hitting ✕ used to raise the window.
  function onRootMouseDown(e: MouseEvent) {
    // Blocked by a window-modal dialog: the click landed on its backdrop.
    if (isBlocked) {
      ctx.store.dismissDialogFor(win.id);
      return;
    }
    if ((e.target as HTMLElement).closest(".pwm-window-controls")) return;
    onFocus();
  }

  // ---- Drag --------------------------------------------------------------
  function capturePointer(el: Element, pointerId: number) {
    try {
      el.setPointerCapture?.(pointerId);
    } catch {
      /* no active pointer */
    }
  }

  function releasePointer(el: Element, pointerId: number) {
    try {
      el.releasePointerCapture?.(pointerId);
    } catch {
      /* already released */
    }
  }

  function onHeaderPointerDown(e: PointerEvent) {
    if (win.isMaximized || isMobile || e.button !== 0) return;

    const now = Date.now();
    if (now - lastClick < DOUBLE_CLICK_THRESHOLD) {
      lastClick = 0;
      return; // second click of a double-click → let dblclick handle it
    }
    lastClick = now;

    onFocus();

    const strip = e.currentTarget as HTMLElement;

    let initialX = win.x;
    let initialY = win.y;

    const startX = e.clientX;
    const startY = e.clientY;

    // A snapped window unsnaps only once the pointer travels, not on a bare click.
    let pendingUnsnap = !!win.isSnapped;
    dragging = !pendingUnsnap;

    const move = (ev: PointerEvent) => {
      if (pendingUnsnap) {
        if (Math.abs(ev.clientX - startX) < UNSNAP_DRAG_THRESHOLD && Math.abs(ev.clientY - startY) < UNSNAP_DRAG_THRESHOLD) {
          return;
        }
        pendingUnsnap = false;

        const pre = ctx.store.getPreSnapBounds(win.id);
        if (pre) {
          // The rect it currently occupies, before the store drops the snap.
          const from = {
            x: win.x,
            y: win.y,
            width: win.width,
            height: win.height,
          };
          const pct = (startX - win.x) / win.width;
          initialX = startX - pre.width * pct;
          initialY = startY - 20;
          // Where it lands this frame: the same position committed just below.
          flip = computeUnsnapFlip(from, {
            x: initialX + (ev.clientX - startX),
            y: initialY + (ev.clientY - startY),
            width: pre.width,
            height: pre.height,
          });
          ctx.store.unSnapWindow(win.id);
        }
        // Position tracks the pointer; transitioning it too makes the window rubber-band.
        dragging = true;
        unsnapping = true;
        unsnapTimer = setTimeout(() => {
          unsnapTimer = null;
          unsnapping = false;
          flip = null;
        }, PWM_UNSNAP_ANIMATION_MS);
      }

      // Once dragged, the position is the user's: stop re-centring.
      userMoved = true;
      ctx.store.updateWindowPosition(win.id, initialX + (ev.clientX - startX), initialY + (ev.clientY - startY));
      if (!isMobile && caps.maximizable) {
        ctx.store.setSnapPreview(detectSnapEdge(ev.clientX, window.innerWidth));
      }
    };
    const up = () => {
      if (ctx.store.snapPreview && !isMobile && caps.maximizable) {
        ctx.store.snapWindow(win.id, ctx.store.snapPreview, taskbarHeight);
      }
      ctx.store.clearSnapPreview();
      if (unsnapTimer) {
        clearTimeout(unsnapTimer);
        unsnapTimer = null;
      }
      unsnapping = false;
      flip = null;
      dragging = false;
      releasePointer(strip, e.pointerId);
      strip.removeEventListener("pointermove", move);
      strip.removeEventListener("pointerup", up);
      strip.removeEventListener("pointercancel", up);
    };
    capturePointer(strip, e.pointerId);
    strip.addEventListener("pointermove", move);
    strip.addEventListener("pointerup", up);
    strip.addEventListener("pointercancel", up);
    e.preventDefault();
  }

  function onHeaderDblClick(e: MouseEvent) {
    if (caps.maximizable) ctx.store.toggleMaximize(win.id);
    e.preventDefault();
    e.stopPropagation();
  }

  // ---- Resize (math in core) -------------------------------------------
  function onResizeStart(direction: ResizeDirection, e: PointerEvent) {
    if (win.isMaximized) return;
    e.stopPropagation();

    const handle = e.currentTarget as HTMLElement;

    const startX = e.clientX;
    const startY = e.clientY;
    const initialWidth = win.width;
    const initialHeight = win.height;
    const initialX = win.x;
    const initialY = win.y;

    onFocus();
    resizing = true;

    const move = (ev: PointerEvent) => {
      const b = computeResize({
        direction,
        deltaX: ev.clientX - startX,
        deltaY: ev.clientY - startY,
        initialX,
        initialY,
        initialWidth,
        initialHeight,
        minWidth: caps.minWidth,
        minHeight: caps.minHeight,
        maxWidth: caps.maxWidth,
        maxHeight: caps.maxHeight,
      });
      ctx.store.updateWindowSize(win.id, b.width, b.height);
      if (b.x !== initialX || b.y !== initialY) {
        ctx.store.updateWindowPosition(win.id, b.x, b.y);
      }
    };
    const up = () => {
      resizing = false;
      releasePointer(handle, e.pointerId);
      handle.removeEventListener("pointermove", move);
      handle.removeEventListener("pointerup", up);
      handle.removeEventListener("pointercancel", up);
    };
    capturePointer(handle, e.pointerId);
    handle.addEventListener("pointermove", move);
    handle.addEventListener("pointerup", up);
    handle.addEventListener("pointercancel", up);
    e.preventDefault();
  }
</script>

<!-- svelte-ignore a11y-no-static-element-interactions -->
<div bind:this={rootEl} class={className} {style} data-pwm-window={win.id} data-pwm-blocked={isBlocked ? "" : undefined} data-pwm-autoheight={win.autoHeight ? "" : undefined} on:mousedown={onRootMouseDown}>
  <!-- svelte-ignore a11y-no-static-element-interactions -->
  <div class={cx("pwm-window-header", classes.titleBar)} inert={isBlocked || undefined}>
    <!-- On the strip, not the header: there, pressing ✕ would start a drag. -->
    <!-- svelte-ignore a11y-no-static-element-interactions -->
    <div class="pwm-window-header-draggable" on:pointerdown={onHeaderPointerDown} on:dblclick={onHeaderDblClick}>
      <div class={cx("pwm-window-icon-container", isActive ? classes.iconContainerActive : classes.iconContainer)}>
        <slot name="icon" {win}><ControlGlyph kind="window" /></slot>
      </div>
      <span class={cx("pwm-window-title", isActive ? classes.titleActive : classes.title)}>
        {win.title}
        <slot name="titleBarExtra" {win} />
      </span>
    </div>

    <div class="pwm-window-controls">
      <!-- Ordered in the DOM, not with CSS `order`: -->
      {#each controlOrder as kind (kind)}
        {#if kind === "minimize" && caps.minimizable}
          <button type="button" class={cx("pwm-window-control pwm-minimize", classes.control)} title={ctx.labels.minimize} aria-label="minimize" on:click|stopPropagation={() => ctx.store.minimizeWindow(win.id)}>
            <slot name="minimize-icon" {win}><ControlGlyph kind="minimize" /></slot>
          </button>
        {:else if kind === "maximize" && !isMobile && caps.maximizable}
          <button type="button" class={cx("pwm-window-control pwm-maximize", classes.control)} title={win.isMaximized ? ctx.labels.restore : ctx.labels.maximize} aria-label="maximize" on:click|stopPropagation={() => ctx.store.toggleMaximize(win.id)}>
            <slot name="maximize-icon" {win}>
              <ControlGlyph kind={win.isMaximized ? "restore" : "maximize"} />
            </slot>
          </button>
        {:else if kind === "close" && caps.closeable}
          <button type="button" class={cx("pwm-window-control pwm-close", classes.closeControl)} title={ctx.labels.close} aria-label="close" on:click|stopPropagation={() => ctx.requestClose(win.id)}>
            <slot name="close-icon" {win}><ControlGlyph kind="close" /></slot>
          </button>
        {/if}
      {/each}
    </div>
  </div>

  <div class={cx("pwm-window-body", classes.body)} inert={isBlocked || undefined}>
    <!-- The host paints this one itself (a <PrismDialog> slot). -->
    {#if win.external}
      <div class="pwm-window-slot" data-pwm-slot={win.id}></div>
    {:else if resolved && keepAlive}
      <svelte:component this={resolved} {...win.data} />
    {:else}
      <slot name="loading"><LoadingGlyph /></slot>
    {/if}
  </div>

  {#if !win.isMaximized && !isMobile && caps.resizable}
    {#each RESIZE_DIRS as dir (dir)}
      <!-- svelte-ignore a11y-no-static-element-interactions -->
      <div class="pwm-resize-handle pwm-resize-{dir}" on:pointerdown={(e) => onResizeStart(dir, e)}></div>
    {/each}
  {/if}
</div>

// packages/vue/src/PrismWindow.vue
<!--
  Prism Window Manager (@prism-wm), Vue 3 adapter
  Copyright (C) 2023-2026 Banshee Technologies S.L.
  Authors: Claudio González, Néstor González
  https://www.banshee.pro/

  Extracted from HomeDock OS: https://github.com/BansheeTech/HomeDockOS

  @license AGPL-3.0-or-later

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with this program. If not, see <https://www.gnu.org/licenses/>.

  SPDX-License-Identifier: AGPL-3.0-or-later
-->
<template>
  <div
    v-show="!window.isMinimized || minimizing"
    class="pwm-window"
    :class="[
      cls.window,
      isActive ? cls.windowActive : cls.windowInactive,
      {
        'pwm-active': isActive,
        'pwm-dialog': window.kind === 'dialog',
        'pwm-maximized': window.isMaximized,
        'pwm-fullscreen-mobile': ctx.isMobile.value && window.kind !== 'dialog',
        'pwm-dragging': dragging,
        'pwm-resizing': resizing,
        'pwm-closing': window.isClosing,
        'pwm-unsnapping': unsnapping,
        'pwm-minimizing': minimizing,
        'pwm-restoring': restoring,
        'pwm-opening': opening,
        [`pwm-${ctx.appearance.value}`]: true,
      },
    ]"
    ref="rootEl"
    :data-pwm-window="window.id"
    :data-pwm-blocked="isBlocked ? '' : undefined"
    :data-pwm-autoheight="window.autoHeight ? '' : undefined"
    :style="[windowStyle, flipVars]"
    @mousedown="onRootMouseDown"
  >
    <div class="pwm-window-header" :class="cls.titleBar" :inert="isBlocked || undefined">
      <!-- On the strip, not the header: there, pressing ✕ would start a drag. -->
      <div class="pwm-window-header-draggable" @pointerdown="onHeaderPointerDown" @dblclick="onHeaderDblClick">
        <div class="pwm-window-icon-container" :class="isActive ? cls.iconContainerActive : cls.iconContainer">
          <slot name="icon" :window="window">
            <svg class="pwm-fallback-icon" data-glyph="window" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
              <path d="M21.53 5.15a.99.99 0 0 0-.97-.04l-10 5a1 1 0 0 0-.55.89v10a1 1 0 0 0 1 1c.15 0 .31-.04.45-.11l10-5a1 1 0 0 0 .55-.89V6c0-.35-.18-.67-.47-.85ZM20 15.38l-8 4v-7.76l8-4z" />
              <path d="m16.55 3.11l-10 5A1 1 0 0 0 6 9v10h2V9.62l9.45-4.72l-.89-1.79Z" />
              <path d="m12.55 1.11l-10 5A1 1 0 0 0 2 7v10h2V7.62l9.45-4.73l-.89-1.79Z" />
            </svg>
          </slot>
        </div>
        <span class="pwm-window-title" :class="isActive ? cls.titleActive : cls.title">
          {{ window.title }}
          <slot name="titleBarExtra" :window="window" />
        </span>
      </div>

      <div class="pwm-window-controls">
        <!-- Ordered in the DOM, not with CSS `order`: -->
        <template v-for="kind in controlOrder" :key="kind">
          <button v-if="kind === 'minimize' && caps.minimizable" type="button" class="pwm-window-control pwm-minimize" :class="cls.control" :title="ctx.labels.minimize" aria-label="minimize" @click.stop="onMinimize">
            <slot name="minimize-icon" :window="window">
              <svg class="pwm-fallback-icon" data-glyph="minimize" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true">
                <path d="M5 12h14" />
              </svg>
            </slot>
          </button>
          <button v-else-if="kind === 'maximize' && !ctx.isMobile.value && caps.maximizable" type="button" class="pwm-window-control pwm-maximize" :class="cls.control" :title="window.isMaximized ? ctx.labels.restore : ctx.labels.maximize" aria-label="maximize" @click.stop="onToggleMaximize">
            <!-- Scoped so hosts can swap maximize/restore glyphs per window. -->
            <slot name="maximize-icon" :window="window">
              <svg class="pwm-fallback-icon" :data-glyph="window.isMaximized ? 'restore' : 'maximize'" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round" aria-hidden="true">
                <template v-if="window.isMaximized">
                  <path d="M8.5 8.5V6.5A1.5 1.5 0 0 1 10 5h7.5A1.5 1.5 0 0 1 19 6.5V14a1.5 1.5 0 0 1-1.5 1.5h-2" />
                  <rect x="5" y="8.5" width="10.5" height="10.5" rx="1.5" />
                  <path d="M5 12h10.5" />
                </template>
                <template v-else>
                  <rect x="5" y="5" width="14" height="14" rx="1.5" />
                  <path d="M5 9h14" />
                </template>
              </svg>
            </slot>
          </button>
          <button v-else-if="kind === 'close' && caps.closeable" type="button" class="pwm-window-control pwm-close" :class="cls.closeControl" :title="ctx.labels.close" aria-label="close" @click.stop="onClose">
            <slot name="close-icon" :window="window">
              <svg class="pwm-fallback-icon" data-glyph="close" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true">
                <path d="M6 6l12 12M18 6L6 18" />
              </svg>
            </slot>
          </button>
        </template>
      </div>
    </div>

    <div class="pwm-window-body" :class="cls.body" :inert="isBlocked || undefined">
      <!-- The host paints this one itself (a <PrismDialog> slot). -->
      <div v-if="window.external" class="pwm-window-slot" :data-pwm-slot="window.id" />
      <component :is="resolved" v-else-if="resolved && keepAlive" v-bind="window.data" />
      <!-- Default rather than an empty body: -->
      <slot v-else name="loading">
        <div class="pwm-window-loading">
          <svg class="pwm-loading-icon" viewBox="0 0 24 24" fill="none" role="status" aria-label="Loading">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 3c4.97 0 9 4.03 9 9" />
          </svg>
        </div>
      </slot>
    </div>

    <template v-if="!window.isMaximized && !ctx.isMobile.value && caps.resizable">
      <div v-for="dir in RESIZE_DIRS" :key="dir" class="pwm-resize-handle" :class="`pwm-resize-${dir}`" @pointerdown.stop="(e: PointerEvent) => onResizeStart(dir, e)"></div>
    </template>
  </div>
</template>

<script lang="ts" setup>
import { computed, inject, markRaw, onMounted, onUnmounted, ref, watch } from "vue";
import { computeResize, detectSnapEdge, centerDialog, computeUnsnapFlip, prefersReducedMotion, PWM_MINIMIZE_ANIMATION_MS, PWM_OPEN_ANIMATION_MS, PWM_UNSNAP_ANIMATION_MS, UNSNAP_DRAG_THRESHOLD, type ResizeDirection, type UnsnapFlip, type WindowState } from "@prism-wm/core";
import { PRISM_CONTEXT, resolveCapabilities } from "./context";

// No withDefaults:
const props = withDefaults(
  defineProps<{
    window: WindowState;
    isActive: boolean;
    // A window-modal dialog belongs to this window: block and inert it.
    isBlocked?: boolean;
  }>(),
  { isBlocked: false },
);

const injected = inject(PRISM_CONTEXT);
if (!injected) {
  throw new Error("PrismWindow must be used inside PrismWindowManager");
}
// Rebound to a const so TS keeps the narrowing inside the handler closures.
const ctx = injected;

// Host theme classes, unwrapped here so the template stays terse.
const cls = computed(() => ctx.classes.value);

// Re-centres as the height changes; stops once the user drags.
const rootEl = ref<HTMLElement | null>(null);
const userMoved = ref(false);
let sizeObserver: ResizeObserver | null = null;

function recentre(h: number) {
  // Reported first: the drag clamp needs the true height, not the placeholder.
  ctx.store.setMeasuredHeight(props.window.id, h);
  if (userMoved.value) return;
  // Same centring rule as the store used, now with the measured height.
  const owner = props.window.modality === "window" && props.window.ownerId ? ctx.store.getWindowById(props.window.ownerId) : null;
  const at = centerDialog(props.window.width, h, { width: window.innerWidth, height: window.innerHeight }, owner);
  ctx.store.updateWindowPosition(props.window.id, at.x, at.y);
}

onMounted(() => {
  if (!props.window.autoHeight || !rootEl.value) return;
  // onMounted runs before paint, so the correction lands in the same frame.
  recentre(rootEl.value.offsetHeight);

  if (typeof ResizeObserver === "undefined") return;
  sizeObserver = new ResizeObserver(() => {
    const h = rootEl.value?.offsetHeight;
    if (h) recentre(h);
  });
  sizeObserver.observe(rootEl.value);
});

onUnmounted(() => {
  sizeObserver?.disconnect();
  sizeObserver = null;
});

const RESIZE_DIRS: ResizeDirection[] = ["n", "s", "e", "w", "ne", "nw", "se", "sw"];

const DOUBLE_CLICK_THRESHOLD = 300;

// Which control sits where, per appearance. See PrismAppearance in core.
const controlOrder = computed(() => (ctx.appearance.value === "cupertino" ? (["close", "minimize", "maximize"] as const) : (["minimize", "maximize", "close"] as const)));

const caps = computed(() => {
  // A dialog is a window with fewer verbs:
  const c = resolveCapabilities(ctx.resolveConfig(props.window));
  if (props.window.kind !== "dialog") return c;
  return { ...c, resizable: false, minimizable: false, maximizable: false };
});

const resolved = computed(() => {
  const c = ctx.resolveComponent(props.window);
  return c ? markRaw(c as object) : null;
});

// ---- Entrance animation ------------------------------------------------
// A class the adapter drops after one run: on .pwm-window it would replay.
const opening = ref(!prefersReducedMotion());
const openTimer = opening.value ? setTimeout(() => (opening.value = false), PWM_OPEN_ANIMATION_MS) : null;

// ---- Minimize / restore animation --------------------------------------
const minimizing = ref(false);
const restoring = ref(false);
let minimizeTimer: ReturnType<typeof setTimeout> | null = null;

watch(
  () => props.window.isMinimized,
  (min) => {
    if (minimizeTimer) clearTimeout(minimizeTimer);
    if (prefersReducedMotion()) {
      minimizing.value = false;
      restoring.value = false;
      return;
    }
    minimizing.value = min;
    restoring.value = !min;
    minimizeTimer = setTimeout(() => {
      minimizeTimer = null;
      minimizing.value = false;
      restoring.value = false;
    }, PWM_MINIMIZE_ANIMATION_MS);
  },
);

// ---- RAM manager: keep-alive gate for the body only --------------------
const keepAlive = ref(true);
watch(
  () => props.window.isMinimized,
  (min) => {
    if (!ctx.ram) return;
    if (min) ctx.ram.onMinimize(props.window.id, () => (keepAlive.value = false));
    else {
      ctx.ram.onRestore(props.window.id);
      keepAlive.value = true;
    }
  },
  { immediate: true },
);

// ---- Geometry / style --------------------------------------------------
const viewport = () => ({
  width: typeof window !== "undefined" ? window.innerWidth : 1920,
  height: typeof window !== "undefined" ? window.innerHeight : 1080,
});

// Read by the pwm-unsnap keyframes and inherited by the body for its counter-scale.
const flipVars = computed(() =>
  flip.value
    ? {
        "--pwm-unsnap-from": flip.value.transform,
        "--pwm-unsnap-from-content": flip.value.contentTransform,
      }
    : {},
);

const windowStyle = computed(() => {
  // Dialogs keep their centred bounds on mobile; only plain windows go fullscreen.
  if (ctx.isMobile.value && props.window.kind !== "dialog") {
    return {
      top: "0",
      left: "0",
      width: "100vw",
      height: `calc(100% - ${ctx.taskbarHeight.value}px)`,
      zIndex: props.window.zIndex,
    };
  }
  if (props.window.isMaximized) {
    return {
      top: "0",
      left: "0",
      width: "100%",
      height: `calc(100% - ${ctx.taskbarHeight.value}px)`,
      zIndex: props.window.zIndex,
    };
  }
  return {
    top: `${props.window.y}px`,
    left: `${props.window.x}px`,
    width: `${props.window.width}px`,
    // Omitted when the content decides: CSS caps it instead.
    height: props.window.autoHeight ? undefined : `${props.window.height}px`,
    zIndex: props.window.zIndex,
  };
});

// ---- Focus / controls --------------------------------------------------
function onFocus() {
  if (!props.isActive) ctx.store.focusWindow(props.window.id);
}

// Focus on mousedown, minus the controls: hitting ✕ used to raise the window.
function onRootMouseDown(e: MouseEvent) {
  // Blocked by a window-modal dialog: the click landed on its backdrop.
  if (props.isBlocked) {
    ctx.store.dismissDialogFor(props.window.id);
    return;
  }
  if ((e.target as HTMLElement).closest(".pwm-window-controls")) return;
  onFocus();
}
function onMinimize() {
  ctx.store.minimizeWindow(props.window.id);
}
function onToggleMaximize() {
  ctx.store.toggleMaximize(props.window.id);
}
function onClose() {
  void ctx.requestClose(props.window.id);
}

// ---- Drag ----------------------------------------------------------------
const dragging = ref(false);
let lastClick = 0;
let unsnapTimer: ReturnType<typeof setTimeout> | null = null;
const unsnapping = ref(false);
const flip = ref<UnsnapFlip | null>(null);

function capturePointer(el: Element, pointerId: number) {
  try {
    el.setPointerCapture?.(pointerId);
  } catch {
    /* no active pointer */
  }
}

function releasePointer(el: Element, pointerId: number) {
  try {
    el.releasePointerCapture?.(pointerId);
  } catch {
    /* already released */
  }
}

function onHeaderPointerDown(e: PointerEvent) {
  if (props.window.isMaximized || ctx.isMobile.value || e.button !== 0) return;

  const now = Date.now();
  if (now - lastClick < DOUBLE_CLICK_THRESHOLD) {
    lastClick = 0;
    return; // second click of a double-click → let dblclick handle it
  }
  lastClick = now;

  onFocus();

  const strip = e.currentTarget as HTMLElement;

  let initialX = props.window.x;
  let initialY = props.window.y;

  const startX = e.clientX;
  const startY = e.clientY;

  // A snapped window unsnaps only once the pointer travels, not on a bare click.
  let pendingUnsnap = !!props.window.isSnapped;
  dragging.value = !pendingUnsnap;

  const move = (ev: PointerEvent) => {
    if (pendingUnsnap) {
      if (Math.abs(ev.clientX - startX) < UNSNAP_DRAG_THRESHOLD && Math.abs(ev.clientY - startY) < UNSNAP_DRAG_THRESHOLD) {
        return;
      }
      pendingUnsnap = false;

      const pre = ctx.store.getPreSnapBounds(props.window.id);
      if (pre) {
        // The rect it currently occupies, before the store drops the snap.
        const from = {
          x: props.window.x,
          y: props.window.y,
          width: props.window.width,
          height: props.window.height,
        };
        const pct = (startX - props.window.x) / props.window.width;
        initialX = startX - pre.width * pct;
        initialY = startY - 20;
        // Where it lands this frame: the same position committed just below.
        flip.value = computeUnsnapFlip(from, {
          x: initialX + (ev.clientX - startX),
          y: initialY + (ev.clientY - startY),
          width: pre.width,
          height: pre.height,
        });
        ctx.store.unSnapWindow(props.window.id);
      }
      // Position tracks the pointer; transitioning it too makes the window rubber-band.
      dragging.value = true;
      unsnapping.value = true;
      unsnapTimer = setTimeout(() => {
        unsnapTimer = null;
        unsnapping.value = false;
        flip.value = null;
      }, PWM_UNSNAP_ANIMATION_MS);
    }

    // Once dragged, the position is the user's: stop re-centring.
    userMoved.value = true;
    ctx.store.updateWindowPosition(props.window.id, initialX + (ev.clientX - startX), initialY + (ev.clientY - startY));
    if (!ctx.isMobile.value && caps.value.maximizable) {
      ctx.store.setSnapPreview(detectSnapEdge(ev.clientX, viewport().width));
    }
  };
  const up = () => {
    if (ctx.store.snapPreview && !ctx.isMobile.value && caps.value.maximizable) {
      ctx.store.snapWindow(props.window.id, ctx.store.snapPreview, ctx.taskbarHeight.value);
    }
    ctx.store.clearSnapPreview();
    if (unsnapTimer) {
      clearTimeout(unsnapTimer);
      unsnapTimer = null;
    }
    unsnapping.value = false;
    flip.value = null;
    dragging.value = false;
    releasePointer(strip, e.pointerId);
    strip.removeEventListener("pointermove", move);
    strip.removeEventListener("pointerup", up);
    strip.removeEventListener("pointercancel", up);
  };
  capturePointer(strip, e.pointerId);
  strip.addEventListener("pointermove", move);
  strip.addEventListener("pointerup", up);
  strip.addEventListener("pointercancel", up);
  e.preventDefault();
}

function onHeaderDblClick(e: MouseEvent) {
  if (caps.value.maximizable) onToggleMaximize();
  e.preventDefault();
  e.stopPropagation();
}

// ---- Resize (maths in core) ----------------------------------------------
const resizing = ref(false);

function onResizeStart(direction: ResizeDirection, e: PointerEvent) {
  if (props.window.isMaximized) return;

  const handle = e.currentTarget as HTMLElement;

  const startX = e.clientX;
  const startY = e.clientY;
  const initialWidth = props.window.width;
  const initialHeight = props.window.height;
  const initialX = props.window.x;
  const initialY = props.window.y;

  onFocus();
  resizing.value = true;

  const move = (ev: PointerEvent) => {
    const c = caps.value;
    const b = computeResize({
      direction,
      deltaX: ev.clientX - startX,
      deltaY: ev.clientY - startY,
      initialX,
      initialY,
      initialWidth,
      initialHeight,
      minWidth: c.minWidth,
      minHeight: c.minHeight,
      maxWidth: c.maxWidth,
      maxHeight: c.maxHeight,
    });
    ctx.store.updateWindowSize(props.window.id, b.width, b.height);
    if (b.x !== initialX || b.y !== initialY) {
      ctx.store.updateWindowPosition(props.window.id, b.x, b.y);
    }
  };
  const up = () => {
    resizing.value = false;
    releasePointer(handle, e.pointerId);
    handle.removeEventListener("pointermove", move);
    handle.removeEventListener("pointerup", up);
    handle.removeEventListener("pointercancel", up);
  };
  capturePointer(handle, e.pointerId);
  handle.addEventListener("pointermove", move);
  handle.addEventListener("pointerup", up);
  handle.addEventListener("pointercancel", up);
  e.preventDefault();
  e.stopPropagation();
}

onUnmounted(() => {
  if (openTimer) clearTimeout(openTimer);
  if (unsnapTimer) clearTimeout(unsnapTimer);
  if (minimizeTimer) clearTimeout(minimizeTimer);
  if (ctx.ram) ctx.ram.onRestore(props.window.id);
});
</script>
